server:
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  shutdown: graceful
  port: 12230

spring:
  profiles:
    active: ${PROFILE}
  batch:
    job.enabled: true # true: 앱 구동시 job 실행 함
    jdbc.initialize-schema: never
  jpa:
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_PORT}/unjeong?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: info

global:
  api:
    customer-base-path: /api/customer
    admin-base-path: /api/admin
---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate.ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate.ddl-auto: update
